apiVersion: apps/v1
kind: Deployment
metadata:
  name: argdep
  labels:
    app: myapparg
spec:
  template:
    metadata:
      name: argdeppod
      labels:
        app: myapparg
    spec:
      containers:
      - name: argdeppod
        image: ubuntu:18.04
        args:
          - "sh"
          - "-c"
          - "hostname && uptime && sleep 3600"
  replicas: 1
  selector:
    matchLabels:
      app: myapparg
