apiVersion: apps/v1
kind: Deployment
metadata:
  name: probes-demo
spec:
  selector:
    matchLabels:
      app: probes-demo
  template:
    metadata:
      labels:
        app: probes-demo
    spec:
      containers:
      - name: httpd
        image: kulbhushanmayer/tomcat:readiness_probe
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: probes-demo-svc
spec:
  type: NodePort
  selector:
    app: probes-demo
  ports:
  - port: 8080
    targetPort: 8080
