---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappdep
  labels:
    app: myapp
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
    spec:
      containers:
      - name: httpd-container
        image: httpd

  replicas: 3
  selector:
    matchLabels:
      app: myapp
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service

spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30009
  selector:
    app: myapp

