---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapppod
spec:
  containers:
  - name: httpd
    image: httpd
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-podservice

spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30008
  selector:
    app: myapppod
