# Default values for yogeshtest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: yogeshraheja/devopsinaction
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2"

service:
  type: NodePort
  port: 80
  nodePort: 31099
