apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretdb
  labels:
    app: dbapp
spec:
  template:
    metadata:
      name: dbapp-pod
      labels:
        app: dbapp
    spec:
      containers:
      - name: mysql-container
        image: mysql:8
        envFrom:
        - secretRef:
            name: mysqlcred
  replicas: 1
  selector:
    matchLabels:
      app: dbapp
