apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrettest
  labels:
    app: dbapp
spec:
  template:
    metadata:
      name: dbapp-pod
      labels:
        app: dbapp
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:18.04
        command:
        - "sleep"
        - "3600"
        volumeMounts:
        - name: cred-volume
          mountPath: /etc/cred
      volumes:
      - name: cred-volume
        secret:
          secretName: yogicred
  replicas: 1
  selector:
    matchLabels:
      app: dbapp
